Repository EdwardKN/Monopoly, pull requests merged in 2023-04, with the labels that each got.

#13 borde inte krascha
  constants.js
  game.js
Labels: bug

#15 Game
  constants.js
  fonts/CormorantGaramond-Regular.ttf
  fonts/Verdana.ttf
  game.js
  images/buttons/playerborder.png
  images/menus/playerinfo.png
  images/menus/playerinfobottom.png
  images/menus/playerinfomiddle.png
  images/menus/playerinfotop.png
Labels: bug, enhancement

#16 Game
  game.js
  images/Cards/greencard2.png
  images/buttons/suggestatrade.png
  images/menus/playerinfo.png
Labels: bug, enhancement

#17 buggfixar och förbättringar
  constants.js
  game.js
Labels: bug, enhancement

#30 Bot
  bot.js
  constants.js
  game.js
  index.html
Labels: bug, enhancement

#29 Update issue templates
  .github/ISSUE_TEMPLATE/buggrapport.md
  .github/ISSUE_TEMPLATE/funktionsidé.md
Labels: documentation

#69 Buggfixar
  game.js
Labels: bug

#77 fix med cursor igen och mortgage gata
  constants.js
  game.js
  images/plates/mortgaged.png
Labels: bug

#54 Menu for online + Many bugfixes
  .gitignore
  api.js
  server/Application.js
  server/api.js
  server/config.json
  server/logger.js
Labels: bug, enhancement, online

#95 Buggfix
  game.js
Labels: bug, local
